python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
python NetFlow_ANN.py data_17
python NetFlow_ANN.py data_18
python NetFlow_ANN.py data_19
python NetFlow_ANN.py data_20
python NetFlow_ANN.py data_21
python NetFlow_ANN.py data_22
